### ISSUE TITLE
downsample has been moved to pool

### ISSUE THREAD

**Issue by xhd2015** [aseveryn/deep-qa#12]
relating to this https://github.com/Theano/Theano/issues/4337
when I run 'python2.7 run_nnet.py TRAIN'
it gives  this:
Traceback (most recent call last):
  File "run_nnet.py", line 15, in <module>
    import nn_layers
  File "/media/sf_D_DRIVE/installed/githubs/deep-qa/nn_layers.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample

then I rewrite 'from theano.tensor.signal import downsample' in nn_layers.py to 'from theano.tensor.signal import pool as downsample',
everything works.

**Comment by liudonglei** [comment]
Thanks.
I also face this problem, and I try to reinstall the 0.8.2 version of theano, but failed also.
but your method works.
