### ISSUE TITLE
NotImplementedError: The image and the kernel must have the same type.inputs(float64), kerns(float32)

### ISSUE THREAD

**Issue by SeekPoint** [aseveryn/deep-qa#7]
rzai@rzai00:~/prj/deep-qa$ python run_nnet.py TRAIN
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled)
Running training in the TRAIN setting
y_train (array([0, 1], dtype=int32), array([4370,  348]))
y_dev (array([0, 1], dtype=int32), array([926, 222]))
y_test (array([0, 1], dtype=int32), array([1233,  284]))
q_train (4718, 33)
q_dev (1148, 33)
q_test (1517, 33)
a_train (4718, 40)
a_dev (1148, 40)
a_test (1517, 40)
Generating random vocabulary for word overlap indicator features with dim: 5
Gaussian
Loading word embeddings from TRAIN/emb_aquaint+wiki.txt.gz.ndim=50.bin.npy
Word embedding matrix size: (17023, 50)
batch_size 50
n_epochs 25
learning_rate 0.1
max_norm 0
Traceback (most recent call last):
  File "run_nnet.py", line 500, in <module>
    main()
  File "run_nnet.py", line 189, in main
    nnet_q.set_input((x_q, x_q_overlap))
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 64, in set_input
    self.output = self.output_func(input)
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 88, in output_func
    layer.set_input(cur_input)
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 64, in set_input
    self.output = self.output_func(input)
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 102, in output_func
    layer.set_input(input)
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 64, in set_input
    self.output = self.output_func(input)
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 88, in output_func
    layer.set_input(cur_input)
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 64, in set_input
    self.output = self.output_func(input)
  File "/home/rzai/prj/deep-qa/nn_layers.py", line 435, in output_func
    image_shape=self.input_shape)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/nnet/conv.py", line 151, in conv2d
    return op(input, filters)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 509, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/nnet/conv.py", line 626, in make_node
    "inputs(%s), kerns(%s)" % (_inputs.dtype, _kerns.dtype))
NotImplementedError: The image and the kernel must have the same type.inputs(float64), kerns(float32)
rzai@rzai00:~/prj/deep-qa$

**Comment by SeekPoint** [comment]
THEANO_FLAGS='floatX=float64' python run_nnet.py TRAIN

can solve this problemn

**Comment by naikzinal** [comment]
dear @loveJasmine  where i put the above line in run_nnet.py  ?

**Comment by SeekPoint** [comment]
run 'THEANO_FLAGS='floatX=float64' python run_nnet.py TRAIN'
